[package]
name = "models"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true

dvf.workspace = true
model.workspace = true

axum-login = { workspace = true, optional = true }

[features]
default = [ ]
auth = [ "dep:axum-login" ]

[lints]
workspace = true
