[package]
edition = "2021"
name = "models"
version = "0.1.0"

[dependencies]
serde.workspace = true

dvf.workspace = true
model.workspace = true

axum-login = { workspace = true, optional = true }

[features]
auth = ["dep:axum-login"]
default = []

[lints]
workspace = true
