
[workspace]
resolver = "2"
members = ["crates/*"]

# only for client-side wasm builds
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1

[workspace.dependencies]
axum = { version = "0.7.4", features = ["macros", "tracing"] }
axum-login = "0.13"
base64 = { version = "0.21" }
bytes = "1.5.0"
cfg-if = "1"
color-eyre = "0.6"
console_error_panic_hook = "0.1.7"
console_log = "1"
http = "1"
image = { version = "0.24", features = [ "avif-encoder" ] }
leptos = { version = "0.6", features = ["nightly", "experimental-islands"] }
leptos_axum = { version = "0.6", features = ["experimental-islands"] }
leptos_meta = { version = "0.6", features = ["nightly"] }
leptos_router = { version = "0.6", features = ["nightly"] }
log = "0.4"
server_fn = { version = "0.6", features = ["multipart"] }
serde = { version = "1", features = ["derive"] }
simple_logger = "4.2.0"
surrealdb = { version = "1" }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.5", features = ["full"] }
tracing = { version = "0.1" }
ulid = { version = "1.1", features = [ "serde" ] }
wasm-bindgen = "=0.2.89"

[[workspace.metadata.leptos]]
# this name is used for the wasm, js and css file names
name = "site"

bin-package = "site-server"
lib-package = "site-frontend"

site-root = "target/site"
site-pkg-dir = "pkg"

style-file = "crates/site-app/style/main.scss"
assets-dir = "crates/site-app/public"

site-addr = "127.0.0.1:3000"
reload-port = 3001

browserquery = "defaults"

tailwind-input-file = "crates/site-app/style/main.scss"
tailwind-config-file = "crates/site-app/style/tailwind/tailwind.config.js"

# set by cargo-leptos
watch = false
env = "DEV"

bin-features = []
bin-default-features = false
lib-features = []
lib-default-features = false
lib-profile-release = "wasm-release"

