
[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.lints.rust]
missing_docs = "deny"

[workspace.dependencies]
# staples
serde = { version = "1", features = ["derive"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# errors
# miette = { version = "7", default-features = false, features = [ "derive" ] }
miette = { git = "https://github.com/zkat/miette", rev = "93d3bd118a072c35aa761f0ec74317166ec08113", default-features = false, features = ["derive"] }
thiserror = "2"

# inherited from rambit
crunch = { git = "https://github.com/rambit-systems/rambit" }
dvf =    { git = "https://github.com/rambit-systems/rambit" }
hex =    { git = "https://github.com/rambit-systems/rambit" }
model =  { git = "https://github.com/rambit-systems/rambit" }
repos =  { git = "https://github.com/rambit-systems/rambit" }

# async
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

# app-level http
axum = { version = "0.7", features = ["macros", "tracing"] }
tower = { version = "0.5", features = ["full"] }
tower-http = { version = "0.5", features = ["full"] }

# leptos
leptos = { version = "0.7.0-rc1", features = ["nightly", "tracing", "experimental-islands"] }
leptos_axum = { version = "0.7.0-rc1", features = ["tracing"] }
leptos_meta = { version = "0.7.0-rc1", features = ["tracing"] }
leptos_router = { version = "0.7.0-rc1", features = ["nightly", "tracing"] }
wasm-bindgen = "=0.2.95"
console_error_panic_hook = "0.1"
console_log = "1"

# only for client-side wasm builds
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1

[[workspace.metadata.leptos]]
name = "site"
hash-files = false

bin-package = "site-server"
lib-package = "site-frontend"

site-root = "target/site"
site-pkg-dir = "pkg"

style-file = "crates/site-app/style/main.scss"
assets-dir = "crates/site-app/public"

site-addr = "0.0.0.0:3000"
reload-port = 3001

browserquery = "defaults"

tailwind-input-file = "crates/site-app/style/main.scss"
tailwind-config-file = "crates/site-app/style/tailwind/tailwind.config.js"

# set by cargo-leptos
watch = false
env = "DEV"

bin-features = []
bin-default-features = false
lib-features = []
lib-default-features = false
lib-profile-release = "wasm-release"

