
[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.lints.rust]
missing_docs = "deny"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }

dvf = { git = "https://github.com/rambit-systems/rambit" }
model = { git = "https://github.com/rambit-systems/rambit" }
