
[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
axum = "0.7.4"
cfg-if = "1"
color-eyre = "0.6.2"
console_error_panic_hook = "0.1.7"
console_log = "1"
http = "0.2.9"leptos = { version = "0.5", features = ["nightly", "experimental-islands"] }
leptos_axum = { version = "0.5", features = ["experimental-islands"] }
leptos_meta = { version = "0.5", features = ["nightly"] }
leptos_router = { version = "0.5", features = ["nightly"] }
log = "0.4.20"serde = { version = "1", features = ["derive"] }
simple_logger = "4.2.0"
surrealdb = "1.1.1"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.4", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
wasm-bindgen = "=0.2.89"
