# fly.toml app configuration file generated for picturepro-mono on 2024-02-23T15:08:05-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "picturepro-mono"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[processes]
  app = "site-server"
  surreal = "surreal start --log=info --auth --bind '[::]':8000 file:/data/srdb.db"

[[mounts]]
  source = "surreal_data"
  destination = "/data"
  initial_size = "1gb"
  processes = ["surreal"]
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1gb"
  auto_extend_size_limit = "5gb"

[http_service]
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/"

[checks]
  [checks.surreal_check]
    processes = ["surreal"]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/status"
    port = 8000
    timeout = "10s"
    type = "http"
