
app = "picturepro"

primary_region = "dfw"
swap_size_mb = 2048

[build]
image = "site-server:latest"

[http_service]
auto_start_machines = false
auto_stop_machines = "off"
internal_port = 3000
min_machines_running = 0

[env]
REDB_STORE_PATH = "/data/picturepro-db"
STORAGE_PATH = "/data/picturepro-storage"

[[mounts]]
destination = "/data"
initial_size = "1gb"
source = "picturepro_data"

[[vm]]
size = "shared-cpu-1x"
