
tab_spaces = 2
# hard_tabs = true
fn_single_line = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 80
overflow_delimited_expr = true
reorder_imports = true
struct_field_align_threshold = 20
wrap_comments = true
