
condense_wildcard_suffixes = true
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 80
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
struct_field_align_threshold = 20
tab_spaces = 2
use_field_init_shorthand = true
wrap_comments = true
