
[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
tokio = { version = "1.35.1", features = ["full"] }
color-eyre = "0.6.2"
axum = "0.7.4"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
