[package]
name = "belt"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["bytes", "sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }

[lints]
workspace = true
