[package]
name = "tower-sessions-kv-store"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
kv.workspace = true

tower-sessions.workspace = true

[lints]
workspace = true
