[package]
name = "base-components"
version = "0.1.0"
edition = "2024"

[dependencies]
lsc = { path = "../lsc" }

leptos = { workspace = true }
tracing.workspace = true

[lints]
workspace = true

[features]
default = [ ]
hydrate = [ "leptos/hydrate" ]
ssr = [ "leptos/ssr" ]
