[package]
edition = "2021"
name = "lsc"
version = "0.1.0"

[dependencies]
enum-iterator = "2.1.0"
leptos = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true

[features]
default = []
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr"]
