[package]
name = "site-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
leptos_axum = { workspace = true, optional = true }

lsc = { path = "../lsc" }
prime-domain = { path = "../prime-domain", optional = true }
models = { path = "../models" }

[features]
default = [ ]
hydrate = [ "leptos/hydrate", "lsc/hydrate" ]
ssr = [
  "leptos/ssr", "leptos/tracing", "leptos_meta/ssr", "leptos_router/ssr",
  "lsc/ssr", "dep:leptos_axum", "dep:prime-domain"
]

[lints]
workspace = true
