[package]
name = "site-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
leptos_axum = { workspace = true, optional = true }
server_fn.workspace = true

http.workspace = true
cfg-if.workspace = true
thiserror.workspace = true
serde.workspace = true
bytes = { workspace = true, optional = true }
time = { workspace = true, optional = true }
chrono = { workspace = true }
timeago = { workspace = true, optional = true }
tower-sessions = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

web-sys = { version = "0.3", features = [ "Window", "Location", "EventTarget", "File", "FileList", "FileReaderSync", "Blob" ] }
gloo-file = { version = "0.3", features = [ "futures" ] }

core_types = { path = "../core_types" }
bl = { path = "../bl" }
validation = { path = "../validation" }

auth = { path = "../auth", optional = true }
futures = "0.3.30"

[features]
default = []
hydrate = ["bl/hydrate", "leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = [
  "bl/ssr", "leptos/ssr", "leptos/tracing", "leptos_meta/ssr", "leptos_router/ssr",
  "dep:leptos_axum", "dep:auth", "dep:bytes", "dep:tracing", "dep:tower-sessions",
  "dep:time", "dep:timeago",
]

