[package]
name = "site-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
leptos_axum = { workspace = true, optional = true }
web-sys = { workspace = true, features = [ "Window" ] }

lsc = { path = "../lsc" }
models = { path = "../models" }
auth-domain = { path = "../auth-domain", optional = true }
prime-domain = { path = "../prime-domain", optional = true }

tracing = { workspace = true, optional = true }
either = "1.13.0"

[features]
default = [ ]
hydrate = [ "leptos/hydrate", "lsc/hydrate" ]
ssr = [
  "leptos/ssr", "leptos/tracing", "leptos_meta/ssr", "leptos_router/ssr",
  "lsc/ssr", "dep:leptos_axum", "dep:auth-domain", "dep:prime-domain",
  "dep:tracing",
]

[lints]
workspace = true
