
name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Containerize & Deploy to Fly
        run:  docker load -i $(nix build ".#site-server-container" -L --no-link --print-out-paths) && flyctl deploy --local-only --detach
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
