
name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            keep-outputs = true
            keep-derivations = true
      - name: Use Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build server package
        run: nix build -L

  flake-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            keep-outputs = true
            keep-derivations = true
      - name: Use Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check flake inputs
        uses: DeterminateSystems/flake-checker-action@main
      - name: Run flake checks
        run: nix flake check -L

  fly-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Validate fly.io config
        run: flyctl config validate
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
