
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Check default package
        run: nix flake check
      - name: Deploy to Fly
        run: nix build ".#container" -L && docker load < result && flyctl deploy --local-only -i site-server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
