
name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build server package
        run: nix build

  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run flake checks
        uses: DeterminateSystems/flake-checker-action@main
