
name: CI-CD

on:
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - name: Build server package
        run: nix build
      - name: Run flake checks
        run: nix flake check
